# Generated by Django 4.1.6 on 2023-03-29 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                choices=[
                    ("QnA", "QnA"),
                    ("Free", "Free"),
                    ("Python", "Python"),
                    ("Go", "Go"),
                    ("Javascript", "Javascript"),
                    ("Notice", "Notice"),
                ],
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myboard.category",
            ),
        ),
    ]
